@startuml

set separator none
hide stereotype

<style>
  root {
    BackgroundColor: transparent;
    FontColor: #8b949e;
  }
  // Element,Container,DataStore
  .Element-RWxlbWVudCxDb250YWluZXIsRGF0YVN0b3Jl {
    BackgroundColor: #7d4e00;
    LineColor: #30363d;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #e6edf3;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 200;
  }
  // Element,Container,Frontend
  .Element-RWxlbWVudCxDb250YWluZXIsRnJvbnRlbmQ= {
    BackgroundColor: #0d419d;
    LineColor: #58a6ff;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #e6edf3;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 200;
  }
  // Relationship
  .Relationship-UmVsYXRpb25zaGlw {
    LineThickness: 2;
    LineStyle: 10-10;
    LineColor: #8b949e;
    FontColor: #8b949e;
    FontSize: 24;
    MaximumWidth: 200;
  }
  // Element
  .DeploymentNode-RWxlbWVudA== {
    BackgroundColor: #1f2937;
    LineColor: #30363d;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #e6edf3;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 200;
  }
  // transparent element for relationships in legend
  .Element-Transparent {
    BackgroundColor: transparent;
    LineColor: transparent;
    FontColor: transparent;
  }
</style>

rectangle "==Element" <<DeploymentNode-RWxlbWVudA==>>

database "==Container, DataStore" <<Element-RWxlbWVudCxDb250YWluZXIsRGF0YVN0b3Jl>>

rectangle "==Container, Frontend" <<Element-RWxlbWVudCxDb250YWluZXIsRnJvbnRlbmQ=>>

rectangle "." <<.Element-Transparent>> as 1
1 --> 1 <<Relationship-UmVsYXRpb25zaGlw>> : "Relationship"

@enduml