[package]
name = "outbox-relay"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "outbox-relay"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
sqlx.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
db = { path = "../../crates/db" }
kafka = { path = "../../crates/kafka" }
